app/models/user.rb
db/migrate/20191118135530_add_name_to_users.rb
db/schema.rb

First and last name added to Users with validation
```
rails db:migrate
```

first and last name added to Users with validation

---

app/models/flat.rb
app/models/user.rb
config/routes.rb
db/migrate/20191118141338_create_flats.rb
db/schema.rb
test/models/flat_test.rb

created the routes and model with validations on all columns, please check that I've added enough validations!

Adding in the flats model

---

app/controllers/flats_controller.rb
app/models/flat.rb
app/views/flats/create.html.erb
app/views/flats/index.html.erb
app/views/flats/new.html.erb
app/views/flats/show.html.erb
app/views/pages/home.html.erb
config/routes.rb
db/migrate/20191118150753_change_type_in_flats.rb
db/schema.rb
test/controllers/flats_controller_test.rb

Flat controller added with index action (search) and updates to flat table
``` 
rails db:migrate required
```

flats controller added with index action

---

app/controllers/flats_controller.rb

added the show and find flat methods

Added show method to flats controller

---

db/seeds.rb

Created 5 seeds for flats. No user seeds yet!
Remember to ```rails db:seed```

created seeds for flats

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_form.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_login_modal.html.erb

Homepage front-end code without navbar

Hompage_front_end_without_navbar

---

app/views/pages/home.html.erb

search form method changed from post to get

---

app/views/flats/index.html.erb
app/views/pages/home.html.erb

very simple results page using same cards as on home page

results page for flats

---

app/views/flats/show.html.erb
app/views/pages/home.html.erb

basic show functionality added to be updated (want updated version of master to continue)

basic show functionality added to be updated

---

app/assets/stylesheets/components/_cards.scss
app/views/flats/index.html.erb

added the cards as a link to the show page

links to show page

---

db/seeds.rb

creating a few more seeds so that i can check margin and padding on the index page
remember to ```rails db:seed```

creating more seeds

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_homepage_banner.scss
app/assets/stylesheets/components/_nomad_logo.scss
app/views/pages/home.html.erb

Organised Logo and signup/login spacing ready to asign a signup modal in the morning!

Sorted logo and signup-logo spacing and colours

---

app/models/booking.rb
app/models/flat.rb
app/models/user.rb
config/routes.rb
db/migrate/20191118201723_create_bookings.rb
test/models/booking_test.rb

Bookings model and routes added. Bookings routes nested inside flats so that a flat can be passed as a param to the bookings#new action. Will also need to use 'current_user' to get id of current user to pass to bookings#new
```
run RAILS DB:MIGRATE
```

bookings model and routes added

---

app/views/flats/show.html.erb

Added skeleton for flat show page. Booking form format looks strange because f.inputs can't be configured without bookings model.

Flat show card added

---

app/controllers/flats_controller.rb
app/models/flat.rb
app/views/flats/index.html.erb
app/views/flats/new.html.erb
db/schema.rb

I still need to add some javascript into the price field as this should display numbers as the user adjusts the range.
I also made some changes to the Flats validations as the form broke with 'presence true' on the checkbox form items for electricity/drinking water.

simple form for adding a new flat

---

app/assets/stylesheets/components/_homepage_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal.scss
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_error_messages.html.erb
app/views/shared/_links.html.erb
app/views/shared/_login_modal.html.erb
app/views/shared/_signup_modal.html.erb

Hi guys updated the link and sign up button not much css but should work fine. left login and sign up links on there.. to be tackled at a later day. problay need to use if statements depending on which view we are in.

Fixed login link and sign up link - not much style

---

app/assets/stylesheets/components/_modal.scss
app/views/shared/_error_messages.html.erb
app/views/shared/_links.html.erb
app/views/shared/_signup_modal.html.erb

Hi please someone review this. just added some small css to the modal form

Added basic style to modal-form to sign up login

---

app/controllers/reviews_controller.rb
app/models/booking.rb
app/models/review.rb
app/views/reviews/new.html.erb
test/controllers/models_controller_test.rb
test/controllers/reviews_controller_test.rb

I have added the controller and have started creating the methods - would like this request merged so that i can pull from master again. Thanks

Created reviews controller and new review method

---

app/models/review.rb
db/migrate/20191119144517_create_reviews.rb
db/schema.rb
test/models/review_test.rb

don't forget to ```rails db:migrate``` !

created Review model

---

.gitignore
app/views/flats/show.html.erb

Please check if you are getting a conflict doug

Add dotenv - Protect my secret data in .env file

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_nomad_logo.scss
app/views/shared/_navbar.html.erb

changed size of logo and avatar on navbar

---

app/views/shared/_navbar.html.erb

Simple change moved if statement above a div so it didn't mess with my css on navbar buttons.

moved login and siginup button

---

app/controllers/reviews_controller.rb
app/views/reviews/_review_form.html.erb
app/views/reviews/_review_index.html.erb
app/views/reviews/new.html.erb

The views will be from the Flat show page - just need to add the forms and buttons (partial created for form and index)

Added controller actions, haven't done views yet

---

app/assets/stylesheets/pages/_show.scss
app/views/flats/show.html.erb

Edit & Delete buttons now in their own div, their own box, and css on both
Icons enlarged, all moved into one div & centered
other formatting changes

showpage_redesign2

---

app/views/bookings/_new.html.erb
app/views/bookings/new.html.erb

changed request booking button

changed requestbookingbutton to nomad theme colour -darkgreen

---

app/views/flats/show.html.erb

carousel images re-sized to fit to width of container

carousel images fit to width of container

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_new_booking_form.scss
app/assets/stylesheets/components/_new_booking_partial.scss
app/views/bookings/_new.html.erb
app/views/bookings/edit.html.erb
app/views/bookings/index.html.erb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb

Refactored and included comments in the bookings views, including adding CSS components for the forms.

Bookings refactor and comments

---

app/views/flats/_nomad_carousel.html.erb
app/views/flats/show.html.erb
db/schema.rb

refactor of carousel code 
In flat show page, carousel now rendered & partial page created for the carousel code itself
At the moment there you can only see one photo as the other generic images have been commented out until we update cloudinary so the host can upload multiple images

carousel refactor

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_nomad_button.scss
app/views/flats/_flats_facitily_card.html.erb
app/views/flats/show.html.erb
db/schema.rb

This might conflict your code Doug!
Refactored the show page and added a partial file to render flats facility card and corrected indents.

refactored show page facility card and button div

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_show.scss

I have added font size padding and opacity

added font size padding and opacity

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_logo.scss
app/assets/stylesheets/components/_modal.scss
app/views/shared/_navbar.html.erb

changed colour theme

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss

made z index higher so nav bar is always on top

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss

Changed banner and navbar vw 100 put margin on the buttons div to reposition

login buttons no longer leave whiet space where scroll bar was

---

app/assets/stylesheets/components/_navbar.scss

Quick change, margin added to reposition for last commit on navbar and banner

avatar needed margin due to previous change, navbar and banner 100vw

---

app/views/flats/_flat_grid.html.erb
app/views/flats/_info_window.html.erb
app/views/flats/_nomad_carousel.html.erb
db/seeds.rb

made some syntax changes in the views files to accomodate for the has_many method added this morning
changed photo to photos

changes to image sizes

---

app/controllers/bookings_controller.rb
db/schema.rb

changed the redirect to in the update def of bookings controller
This keeps the user on the bookings page once clicking on confirm in the bookings request on the dashboard.

bookings controller update

---

app/views/users/_host_flat_list.html.erb

host_flats partial updated so that flat images showing on cards

---

app/assets/stylesheets/components/_navbar.scss

removed box shadow on navbar avatar

---

app/assets/stylesheets/components/_button.scss
app/views/bookings/_new.html.erb

moved button to book and changed colour to colour theme

rewuest button colour change and centered on form

---

db/seeds.rb

updated seed examples to showcase carousel

seed examples update

---

db/seeds.rb

added another seed example for the demo

seed update 2

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_map.scss
app/views/flats/_flat_grid.html.erb
app/views/flats/index.html.erb

included bootstrap responsive grid in flats index page

---

app/models/review.rb
app/views/reviews/_new.html.erb

changed the limit on the reviews so it gives you a choice of 1 to 5

ratings number change

---

app/assets/stylesheets/components/_cards.scss
app/views/users/_upcoming_bookings.html.erb
app/views/users/show.html.erb

changed styling of upcoming bookings card

---

app/views/flats/_review_form.html.erb

previous listings with reviews came up with an error when clicking on them
I've changed the code in in _review_form.html.erb to show the reviews when you're both logged out and when you're logged in as a user

listings with reviews

---

Gemfile.lock

updated to Gem lockfile

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

title added to navbar

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

removed title as per your request

removed title
